apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dad-jokes
  namespace: argocd-demo
spec:
  project: default
  source:
    repoURL: https://github.com/Soyokaze-42/argocd-dad-jokes.git
    path: resources
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: dad-jokes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true