apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: joke-cluster
spec:
  instances: 1

  bootstrap:
    initdb:
      database: app
      owner: app
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: post-init-sql-configmap
          key: configmap.sql

  storage:
    size: 128Mi
