apiVersion: v1
stringData:
  password: #Set a postgresql password (but don't write it to a file)
  username: #Set a postgresql username
kind: Secret
metadata:
  name: db-user
type: kubernetes.io/basic-auth
